version: "2"

linters:
  enable:
    - errcheck
    - govet
    - gosec
    - ineffassign
    - staticcheck
    - unused
    - revive
    - gocritic
    - gocognit
    - misspell

  settings:
    gocognit:
      min-complexity: 30

    gosec:
      excludes:
        - G104

    revive:
      rules:
        - name: var-naming
        - name: blank-imports
        - name: context-as-argument
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: range-val-address
        - name: time-equal
        - name: unconditional-recursion
        - name: waitgroup-by-value

  exclusions:
    generated: lax
    paths:
      - desktop/frontend/wailsjs
      - desktop/frontend/node_modules

formatters:
  enable:
    - gofmt
    - goimports
