// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CloseDocument(arg1:string):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function GetState():Promise<main.State>;

export function IngestSource(arg1:string):Promise<main.DocumentState>;

export function OpenDocument(arg1:string):Promise<void>;

export function PickAndIngestFile():Promise<main.DocumentState>;

export function SaveProfile(arg1:string,arg2:string):Promise<void>;

export function SetActiveProfile(arg1:string):Promise<void>;

export function WarmCache():Promise<void>;
