// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseDocument(arg1) {
  return window['go']['main']['App']['CloseDocument'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function IngestSource(arg1) {
  return window['go']['main']['App']['IngestSource'](arg1);
}

export function OpenDocument(arg1) {
  return window['go']['main']['App']['OpenDocument'](arg1);
}

export function PickAndIngestFile() {
  return window['go']['main']['App']['PickAndIngestFile']();
}

export function SaveProfile(arg1, arg2) {
  return window['go']['main']['App']['SaveProfile'](arg1, arg2);
}

export function SetActiveProfile(arg1) {
  return window['go']['main']['App']['SetActiveProfile'](arg1);
}

export function WarmCache() {
  return window['go']['main']['App']['WarmCache']();
}
